global_frame: odom
robot_base_frame: base_link
rolling_window: true
update_frequency: 30.0
publish_frequency: 30.0
transform_tolerance: 0.2
static_map: false
rolling_window: true
resolution: 0.1
inflation_radius: 0.1
width: 0.1 #2.5
height: 0.1 #2.5
plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}